### ISSUE TITLE
How do you run this on the S23 Ultra please.

### ISSUE THREAD

**Issue by AntDX316** [quic/ai-hub-models#14]
How do you run this and the other QualComm Hub models on the S23 Ultra please?

**Comment by heechan12** [comment]
I'm really curious too, especially about the Stable diffusion...

**Comment by bhushan23** [comment]
There's a device parameter that you can provide while submitting AI Hub jobs to select devices of interest.
e.g. example in https://app.aihub.qualcomm.com/docs/hub/compile_examples.html#compile-a-torchscript-model

In order to get complete list of devices you can run following in cli
```
qai-hub list-devices
```

and then use device name or any attribute of interest to get hub device
e.g. Following is one of the option to get a device with device name
```
hub.Device(name="Samsung Galaxy S23 Ultra")
```
Let's see this in action
```
import qai_hub as hub

# Compile a model
compile_job = hub.submit_compile_job(
    model="mobilenet_v2.pt",
    device=hub.Device("Samsung Galaxy S23 Ultra"),
    input_specs=dict(image=(1, 3, 224, 224)),
)
assert isinstance(compile_job, hub.CompileJob)

# Profile the compiled model
profile_job = hub.submit_profile_job(
    model=compile_job.get_target_model(),
    device=hub.Device("Samsung Galaxy S23 Ultra"),
)
assert isinstance(profile_job, hub.ProfileJob)
```

@heechan12 demo.py does have an option to override default device and you can do so as follow
```
pip install -e ".[stable_diffusion_quantized]"
python -m qai_hub_models.models.stable_diffusion_quantized.demo --device-name "Samsung Galaxy S23 Ultra"
```
