### ISSUE TITLE
[Feature Request] How to run Whisper on the 8550 LE system

### ISSUE THREAD

**Issue by 32zhuyt** [quic/ai-hub-models#53]
Hello，

I want to run Whisper on a GPU on an 8550 device.

Now I have downloaded the source code of qai hub and am able to successfully run `python3- m pytest -- pyargs qai_hub_models.models.whiser_base_en.demo` 、”python 3- m pytest -- pyargs qai_hub_models. models. wheeler_base_en.test” and other commands.

But these commands seem to not be able to see the specific information of converting voice to text. Is there any command that can convert my own audio into text and see the results of GPU operation.

thanks

**Comment by kory** [comment]
Please record your voice into an audio file. The demo was just updated today (v0.9.0) with the ability to translate any file. You can pass --audio_file <path> as a flag to the demo to make that work.

**Comment by ZodiacFRA** [comment]
Hi :) Commenting here rather than opening a new issue, tell me if you'd prefer otherwise.

I'm pretty sure the command you used does not execute Whisper on the 8550, and I too would like to know how running Whisper could be done on the 8550 GPU / NPU with Linux.

I already converted Whisper's encoder into a .dlc format but the doing so for the decoder is not possible: afaik QNN still does not support input tensors with variable shape which are needed for transformers. 

The [Qualcomm AI hub model website](https://aihub.qualcomm.com/mobile/models/whisper_tiny_en?domain=Audio&chipsets=Snapdragon+8+Gen+2) now lists the decoder as available on the 8550 with QNN (=AI Engine Direct) but downloading it provides a .so.

- Which Linux OS should I use on the 8550 ?
- Why is the downloaded model a .so and not a .dlc file? How should I use this shared library?

Have a great day :)
