### ISSUE TITLE
Why Pad before Conv2D in yolov8_det_quantized tflite model

### ISSUE THREAD

**Issue by richjjj** [quic/ai-hub-models#54]
The image is padded from "640 × 640 × 3" to "641×641×3", but why?
![image](https://github.com/quic/ai-hub-models/assets/37280580/91dc1c6c-8af0-4ba8-b63a-fbf07f11ded5)

**Comment by mestrona-3** [comment]
Hi @richjjj, this is because TF-Lite must do it this way to represent top/left asymmetric padding.

For these types of questions, we encourage you to task them on our [Slack Community](https://join.slack.com/t/qualcomm-ai-hub/shared_invite/zt-2j76uzoye-Xya17vQESuxrWTKEwK2uMQ) for faster responses, so that we can connect you with the right engineer!
