### ISSUE TITLE
[BUG] ViT export stopped working correctly

### ISSUE THREAD

**Issue by Lavreniuk** [quic/ai-hub-models#73]
**The model inference time is much slower**

**To Reproduce**
pip install -q qai-hub-models
git clone https://github.com/quic/ai-hub-models
cd ai-hub-models/qai_hub_models/models/vit
python -m qai_hub_models.models.vit.export

**Expected behavior**
here is expected results:
https://aihub.qualcomm.com/jobs/jn5qv9l7g

**Stack trace**
here is my run:
https://app.aihub.qualcomm.com/jobs/jmg9drmw5/
(in your example all layers are in NPU, in my not).

Also if I download weights from your repo from this commit:
https://huggingface.co/qualcomm/VIT/tree/973054da6d5d65b53537f7e608021bded3c4c522
it works fine, but the newest commit it same issue as when I converted by myself (slow inference time).

**Host configuration:**
 - OS and version: Ubuntu 22.04.3 LTS
 - QAI-Hub-Models version: AI Hub : aihub-2024.07.11.0 (in aihub-2024.06.27.0 I got good inference speed, but don't know how I could downgrade with version)
 - qai-hub-models==0.9.2 and 0.10.0 (tried both).

**Comment by mestrona-3** [comment]
Hi @Lavreniuk , thank you for filing this issue! Apologies for the delayed response. This is a known issue due to one of package dependencies in AI Hub. We will fix this once resolved in the dependent package. Please join our [Slack Community](https://aihub.qualcomm.com/community/slack) for release notes on when this issue is resolved.

**Comment by kory** [comment]
Performance for ViT has been improved to 17ms in the newest version of AI Hub Models (https://aihub.qualcomm.com/jobs/j56y4rd0p).
