### ISSUE TITLE
error occured when run llama_v2_7b_chat_quantized_PromptProcessor_3_Quantized

### ISSUE THREAD

**Issue by yolanda1224git** [quic/ai-hub-models#84]
**Describe the issue**
I run llama_v2_7B model in AI-HUB, and llama_v2_7b_chat_quantized_PromptProcessor_3_Quantized reports an error, the reason is "Job timed out after 8h".
inference job is https://app.aihub.qualcomm.com/jobs/jmg9o0jmg/
profiling job is https://app.aihub.qualcomm.com/jobs/jz5wyw24g/.

Other 3 parts run successfully. Only the 3th one run failed.
Could you help to checkout the reason please?

**Comment by bhushan23** [comment]
Hi @yolanda1224git both of the jobs are timed out.
It's mostly due to large wait time when job was submitted.

Could you please resubmit these jobs?
you can use qai-hub APIs to get the model and dataset to avoid model re-upload as follows 
```
>>> import qai_hub as hub
>>> job = hub.get_job('jmg9o0jmg')
>>> hub.submit_inference_job(job.model, inputs=job.inputs, device=job.device)
```

similarly, you can submit profile job with given options.
Please feel free to re-open issue if error persists
